#!/bin/sh

# This startup script gathers hostname, domain, and next_server from DHCP for client

if ! [ -z "${domain}" ]; then
    fqdn="${domain}"
fi

if ! [ -z "${hostname}" ]; then
    host="${hostname}"
fi

if ! [ -z "${siaddr}" ]; then
    next_server="${siaddr}"
fi

echo "${host}" > /etc/hostname
hostname -F /etc/hostname

echo "127.0.0.1 ${host}.${fqdn} ${host} localhost.localdomain   localhost" > /etc/hosts
echo "::1       localhost   localhost.localdomain" >> /etc/hosts

# Store 'next_server' option from DHCP (boot server) on client filesystem for referencing and add as repository mirrors
if ! [ -z "${next_server}" ]; then
    echo "${next_server}" > /etc/next_server
    echo -e "http://${next_server}/alpine/v3.21/main\n$(cat /etc/apk/repositories)" > /etc/apk/repositories
    echo -e "http://${next_server}/alpine/v3.21/community\n$(cat /etc/apk/repositories)" > /etc/apk/repositories
    echo -e "http://${next_server}/alpine/v3.21/mod\n$(cat /etc/apk/repositories)" > /etc/apk/repositories
fi

